### ISSUE TITLE
Snap not working

### ISSUE THREAD

**Issue by kz6fittycent** [kz6fittycent/TunerStudio-snap#1]
## Please follow the general troubleshooting steps first:

- [x] Try running `snap run tunerstudio`
- [x] Refreshing the snap to ensure you have the latest `stable` version
- [x] Restart `snapd`

* Expected behavior -
Snap should start

* Observed behavior - 
```
snap run tunerstudio
Jar Name:TunerStudioMS.jar
10/31/24, 8:42:02 AM :Error: get uninitialized PcActivationManager!
Registration file not found. 
10/31/24, 8:42:02 AM :Debug: Unable to load user properties, looking in:
/snap/tunerstudio/216/bin/TunerStudioMS/.
10/31/24, 8:42:02 AM :Debug: hid: 71.497696
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by TunerStudio (file:/snap/tunerstudio/216/bin/TunerStudioMS/TunerStudioMS.jar) to field java.nio.charset.Charset.defaultCharset
WARNING: Please consider reporting this to the maintainers of TunerStudio
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

* OS Info (Note: Centos and RHEL don't have good support for `snapd`, leading to failed execution) -
`POP!_OS`

* Snap version (`snap info tunerstudio`) - 
`installed:          3.2.03               (216) 387MB`

* Snapd version (run `snap --version`) 
```
snap    2.65.3+22.04
snapd   2.65.3+22.04
series  16
pop     22.04
kernel  6.9.3-76060903-generic
```

* Logs can be pasted here - 
```
snap run tunerstudio
Jar Name:TunerStudioMS.jar
10/31/24, 8:42:02 AM :Error: get uninitialized PcActivationManager!
Registration file not found. 
10/31/24, 8:42:02 AM :Debug: Unable to load user properties, looking in:
/snap/tunerstudio/216/bin/TunerStudioMS/.
10/31/24, 8:42:02 AM :Debug: hid: 71.497696
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by TunerStudio (file:/snap/tunerstudio/216/bin/TunerStudioMS/TunerStudioMS.jar) to field java.nio.charset.Charset.defaultCharset
WARNING: Please consider reporting this to the maintainers of TunerStudio
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

---
### Consider contributing to this project with a PR ###

https://github.com/kz6fittycent/tunerstudio/pulls

**Comment by kz6fittycent** [comment]
See this [link ](https://www.msextra.com/forums/viewtopic.php?t=77498)for more info.

**Comment by kz6fittycent** [comment]
After switching the snap to `openjdk-8`:

```
snap run tunerstudio
libpxbackend-1.0.so: cannot open shared object file: No such file or directory
Failed to load module: /home/james/snap/tunerstudio/common/.cache/gio-modules/libgiolibproxy.so
Jar Name:TunerStudioMS.jar
11/5/24 9:05:22 AM :Error: get uninitialized PcActivationManager!
Registration file not found. 
11/5/24 9:05:22 AM :Debug: Unable to load user properties, looking in:
/snap/tunerstudio/225/bin/TunerStudioMS/.
java.io.IOException: Cannot run program "/usr/bin/xprop": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:593)
	at java.lang.Runtime.exec(Runtime.java:423)
	at java.lang.Runtime.exec(Runtime.java:320)
	at org.GNOME.Accessibility.AtkWrapper.<clinit>(AtkWrapper.java:42)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at java.awt.Toolkit.loadAssistiveTechnologies(Toolkit.java:805)
	at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:886)
	at sun.swing.SwingUtilities2.getSystemMnemonicKeyMask(SwingUtilities2.java:2041)
	at javax.swing.plaf.basic.BasicLookAndFeel.initComponentDefaults(BasicLookAndFeel.java:1158)
	at javax.swing.plaf.metal.MetalLookAndFeel.initComponentDefaults(MetalLookAndFeel.java:431)
	at javax.swing.plaf.basic.BasicLookAndFeel.getDefaults(BasicLookAndFeel.java:148)
	at javax.swing.plaf.metal.MetalLookAndFeel.getDefaults(MetalLookAndFeel.java:1577)
	at javax.swing.UIManager.setLookAndFeel(UIManager.java:539)
	at javax.swing.UIManager.setLookAndFeel(UIManager.java:579)
	at javax.swing.UIManager.initializeDefaultLAF(UIManager.java:1349)
	at javax.swing.UIManager.initialize(UIManager.java:1459)
	at javax.swing.UIManager.maybeInitialize(UIManager.java:1426)
	at javax.swing.UIManager.getDefaults(UIManager.java:659)
	at javax.swing.UIManager.getString(UIManager.java:788)
	at javax.swing.filechooser.UnixFileSystemView.<clinit>(FileSystemView.java:610)
	at javax.swing.filechooser.FileSystemView.getFileSystemView(FileSystemView.java:86)
	at p.j.r(Unknown Source)
	at p.j.t(Unknown Source)
	at TunerStudio.main(Unknown Source)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 28 more
```
